name: TS CI

on:
  push:
    branches: [staging, master]
  pull_request:
    branches: [staging]

jobs:
  eslint:
    name: Run web-linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (pull request)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN_WKK }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Checkout (push)
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN_WKK }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Run eslint
        uses: monclubsportif/web-linter@v1
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          message: "web-linter commit"
  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: eslint

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install Packages
        run: yarn install

      - name: Build site
        run: yarn build

      - name: Run tests
        run: yarn test
